/// @file icons_material.h
/// @brief Embedded SVG icons - Material Design
///
/// This file is AUTO-GENERATED by tools/icon_tools/svg_to_header.py
/// DO NOT EDIT MANUALLY - changes will be overwritten on next generation
///
/// Icon source: Material Design Icons
/// License: Apache License 2.0
/// Repository: https://github.com/google/material-design-icons
///
/// Usage:
/// @code
/// #include "kalahari/resources/icons_material.h"
/// using namespace kalahari::icons::material;
///
/// // Get SVG string
/// const char* svg = FILE_NEW;
///
/// // Register with IconRegistry
/// IconRegistry::getInstance().registerIcon("wxID_NEW", FILE_NEW, "New File");
/// @endcode

#pragma once

#include <string>

namespace kalahari {
namespace icons {
namespace material {

// ============================================================================
// Embedded SVG Icons (22 icons)
// ============================================================================
// Each icon is a constexpr string containing SVG XML.
// The {COLOR} placeholder will be replaced with actual color at runtime.
// ============================================================================

/// @brief Close
constexpr const char* CLOSE = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z"/> </svg>)";

/// @brief Copy
constexpr const char* COPY = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z"/> </svg>)";

/// @brief Cut
constexpr const char* CUT = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M9.64 7.64c.23-.5.36-1.05.36-1.64 0-2.21-1.79-4-4-4S2 3.79 2 6s1.79 4 4 4c.59 0 1.14-.13 1.64-.36L10 12l-2.36 2.36C7.14 14.13 6.59 14 6 14c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4c0-.59-.13-1.14-.36-1.64L12 14l7 7h3v-1L9.64 7.64zM6 8c-1.1 0-2-.89-2-2s.9-2 2-2 2 .89 2 2-.9 2-2 2zm0 12c-1.1 0-2-.89-2-2s.9-2 2-2 2 .89 2 2-.9 2-2 2zm6-7.5c-.28 0-.5-.22-.5-.5s.22-.5.5-.5.5.22.5.5-.22.5-.5.5zM19 3l-6 6 2 2 7-7V3z"/> </svg>)";

/// @brief Delete Icon
constexpr const char* DELETE_ICON = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"/> </svg>)";

/// @brief Error Icon
constexpr const char* ERROR_ICON = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="{COLOR}"> <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/> </svg>)";

/// @brief Exit
constexpr const char* EXIT = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M10.09 15.59L11.5 17l5-5-5-5-1.41 1.41L12.67 11H3v2h9.67l-2.58 2.59zM19 3H5c-1.11 0-2 .9-2 2v4h2V5h14v14H5v-4H3v4c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2z"/> </svg>)";

/// @brief File New
constexpr const char* FILE_NEW = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M14 2H6c-1.1 0-1.99.9-1.99 2L4 20c0 1.1.89 2 1.99 2H18c1.1 0 2-.9 2-2V8l-6-6zm2 16H8v-2h8v2zm0-4H8v-2h8v2zm-3-5V3.5L18.5 9H13z"/> </svg>)";

/// @brief File Open
constexpr const char* FILE_OPEN = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M10 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z"/> </svg>)";

/// @brief Find
constexpr const char* FIND = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M15.5 14h-.79l-.28-.27C15.41 12.59 16 11.11 16 9.5 16 5.91 13.09 3 9.5 3S3 5.91 3 9.5 5.91 16 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z"/> </svg>)";

/// @brief Folder
constexpr const char* FOLDER = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M10 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V8c0-1.1-.9-2-2-2h-8l-2-2z"/> </svg>)";

/// @brief Help
constexpr const char* HELP = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17h-2v-2h2v2zm2.07-7.75l-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/> </svg>)";

/// @brief Info
constexpr const char* INFO = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/> </svg>)";

/// @brief Information
constexpr const char* INFORMATION = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="{COLOR}"> <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z"/> </svg>)";

/// @brief Paste
constexpr const char* PASTE = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M19 2h-4.18C14.4.84 13.3 0 12 0c-1.3 0-2.4.84-2.82 2H5c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-7 0c.55 0 1 .45 1 1s-.45 1-1 1-1-.45-1-1 .45-1 1-1zm7 18H5V4h2v3h10V4h2v16z"/> </svg>)";

/// @brief Print
constexpr const char* PRINT = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M19 8H5c-1.66 0-3 1.34-3 3v6h4v4h12v-4h4v-6c0-1.66-1.34-3-3-3zm-3 11H8v-5h8v5zm3-7c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm-1-9H6v4h12V3z"/> </svg>)";

/// @brief Question
constexpr const char* QUESTION = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="{COLOR}"> <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 17h-2v-2h2v2zm2.07-7.75l-.9.92C13.45 12.9 13 13.5 13 15h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/> </svg>)";

/// @brief Redo
constexpr const char* REDO = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M18.4 10.6C16.55 8.99 14.15 8 11.5 8c-4.65 0-8.58 3.03-9.96 7.22L3.9 16c1.05-3.19 4.05-5.5 7.6-5.5 1.95 0 3.73.72 5.12 1.88L13 16h9V7l-3.6 3.6z"/> </svg>)";

/// @brief Save
constexpr const char* SAVE = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M17 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V7l-4-4zm-5 16c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm3-10H5V5h10v4z"/> </svg>)";

/// @brief Save As
constexpr const char* SAVE_AS = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M17 3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2V7l-4-4zm-5 16c-1.66 0-3-1.34-3-3s1.34-3 3-3 3 1.34 3 3-1.34 3-3 3zm3-10H5V5h10v4z"/> <path fill="{COLOR}" d="M19 2h2v2h-2zm0 4h2v2h-2z"/> </svg>)";

/// @brief Settings
constexpr const char* SETTINGS = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M19.14 12.94c.04-.3.06-.61.06-.94 0-.32-.02-.64-.07-.94l2.03-1.58c.18-.14.23-.41.12-.61l-1.92-3.32c-.12-.22-.37-.29-.59-.22l-2.39.96c-.5-.38-1.03-.7-1.62-.94L14.4 2.81c-.04-.24-.24-.41-.48-.41h-3.84c-.24 0-.43.17-.47.41l-.36 2.54c-.59.24-1.13.57-1.62.94l-2.39-.96c-.22-.08-.47 0-.59.22L2.74 8.87c-.12.21-.08.47.12.61l2.03 1.58c-.05.3-.09.63-.09.94s.02.64.07.94l-2.03 1.58c-.18.14-.23.41-.12.61l1.92 3.32c.12.22.37.29.59.22l2.39-.96c.5.38 1.03.7 1.62.94l.36 2.54c.05.24.24.41.48.41h3.84c.24 0 .44-.17.47-.41l.36-2.54c.59-.24 1.13-.56 1.62-.94l2.39.96c.22.08.47 0 .59-.22l1.92-3.32c.12-.22.07-.47-.12-.61l-2.01-1.58zM12 15.6c-1.98 0-3.6-1.62-3.6-3.6s1.62-3.6 3.6-3.6 3.6 1.62 3.6 3.6-1.62 3.6-3.6 3.6z"/> </svg>)";

/// @brief Undo
constexpr const char* UNDO = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"> <path fill="{COLOR}" d="M12.5 8c-2.65 0-5.05.99-6.9 2.6L2 7v9h9l-3.62-3.62c1.39-1.16 3.16-1.88 5.12-1.88 3.54 0 6.55 2.31 7.6 5.5l2.37-.78C21.08 11.03 17.15 8 12.5 8z"/> </svg>)";

/// @brief Warning
constexpr const char* WARNING = R"(<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="{COLOR}"> <path d="M1 21h22L12 2 1 21zm12-3h-2v-2h2v2zm0-4h-2v-4h2v4z"/> </svg>)";

} // namespace material
} // namespace icons
} // namespace kalahari
