#!/usr/bin/env python3
"""
SVG to C++ Header Converter
============================

Converts SVG icon files to C++ header with embedded SVG strings.

Usage:
    python svg_to_header.py <input_dir> <output_header>

Example:
    python svg_to_header.py resources/icons/material_design \
                            include/kalahari/resources/icons_material.h

Features:
- Converts SVG files to constexpr string literals
- Replaces hardcoded colors with {COLOR} placeholder
- Generates clean C++ namespace structure
- Includes usage documentation in header comments
"""

import os
import re
import sys
from pathlib import Path
from typing import List, Tuple

def sanitize_icon_name(filename: str) -> str:
    """
    Convert filename to C++ constant name.

    Examples:
        file-new.svg -> FILE_NEW
        folder-open.svg -> FOLDER_OPEN
        content_copy.svg -> CONTENT_COPY
    """
    name = Path(filename).stem  # Remove .svg extension
    name = name.upper()  # Uppercase
    name = name.replace('-', '_')  # Replace hyphens
    name = name.replace(' ', '_')  # Replace spaces
    return name


def process_svg_content(svg_content: str) -> str:
    """
    Process SVG content to make it suitable for embedding.

    - Replace common color values with {COLOR} placeholder
    - Normalize whitespace
    - Remove comments
    """
    # Common black/dark colors to replace with {COLOR}
    color_patterns = [
        r'fill="#000000"',
        r'fill="#000"',
        r"fill='#000000'",
        r"fill='#000'",
        r'fill="black"',
        r'fill="currentColor"',
        r'fill="rgb\(0,\s*0,\s*0\)"',
    ]

    result = svg_content
    for pattern in color_patterns:
        result = re.sub(pattern, 'fill="{COLOR}"', result, flags=re.IGNORECASE)

    # Remove XML comments
    result = re.sub(r'<!--.*?-->', '', result, flags=re.DOTALL)

    # Normalize whitespace (but keep structure)
    result = re.sub(r'\s+', ' ', result)
    result = result.strip()

    return result


def generate_header(svg_files: List[Tuple[str, str]], namespace: str = "material") -> str:
    """
    Generate C++ header file content.

    Args:
        svg_files: List of (icon_name, svg_content) tuples
        namespace: Namespace name (default: "material")

    Returns:
        Complete header file content as string
    """
    header = f"""/// @file icons_{namespace}.h
/// @brief Embedded SVG icons - {namespace.capitalize()} Design
///
/// This file is AUTO-GENERATED by tools/icon_tools/svg_to_header.py
/// DO NOT EDIT MANUALLY - changes will be overwritten on next generation
///
/// Icon source: Material Design Icons
/// License: Apache License 2.0
/// Repository: https://github.com/google/material-design-icons
///
/// Usage:
/// @code
/// #include "kalahari/resources/icons_{namespace}.h"
/// using namespace kalahari::icons::{namespace};
///
/// // Get SVG string
/// const char* svg = FILE_NEW;
///
/// // Register with IconRegistry
/// IconRegistry::getInstance().registerIcon("wxID_NEW", FILE_NEW, "New File");
/// @endcode

#pragma once

#include <string>

namespace kalahari {{
namespace icons {{
namespace {namespace} {{

// ============================================================================
// Embedded SVG Icons ({len(svg_files)} icons)
// ============================================================================
// Each icon is a constexpr string containing SVG XML.
// The {{COLOR}} placeholder will be replaced with actual color at runtime.
// ============================================================================

"""

    # Add icon constants
    for icon_name, svg_content in sorted(svg_files):
        # Escape quotes and backslashes for C++ raw string literal
        svg_escaped = svg_content

        header += f"""/// @brief {icon_name.replace('_', ' ').title()}
constexpr const char* {icon_name} = R"({svg_escaped})";

"""

    # Close namespaces
    header += f"""}} // namespace {namespace}
}} // namespace icons
}} // namespace kalahari
"""

    return header


def main():
    if len(sys.argv) != 3:
        print("Usage: python svg_to_header.py <input_dir> <output_header>")
        print()
        print("Example:")
        print("  python svg_to_header.py resources/icons/material_design \\")
        print("                          include/kalahari/resources/icons_material.h")
        sys.exit(1)

    input_dir = Path(sys.argv[1])
    output_file = Path(sys.argv[2])

    if not input_dir.exists() or not input_dir.is_dir():
        print(f"Error: Input directory '{input_dir}' does not exist")
        sys.exit(1)

    # Find all SVG files
    svg_files = list(input_dir.glob("*.svg"))

    if not svg_files:
        print(f"Warning: No SVG files found in '{input_dir}'")
        sys.exit(1)

    print(f"Processing {len(svg_files)} SVG files from '{input_dir}'...")

    # Process all SVG files
    processed_icons = []
    for svg_file in svg_files:
        try:
            with open(svg_file, 'r', encoding='utf-8') as f:
                svg_content = f.read()

            icon_name = sanitize_icon_name(svg_file.name)
            processed_svg = process_svg_content(svg_content)

            processed_icons.append((icon_name, processed_svg))
            print(f"  ✓ {svg_file.name} → {icon_name}")

        except Exception as e:
            print(f"  ✗ {svg_file.name}: {e}")

    if not processed_icons:
        print("Error: No icons processed successfully")
        sys.exit(1)

    # Determine namespace from input directory name
    namespace = input_dir.name
    if namespace.startswith("material"):
        namespace = "material"
    elif namespace.startswith("fontawesome"):
        namespace = "fontawesome"
    else:
        namespace = "custom"

    # Generate header
    print(f"\nGenerating header file '{output_file}'...")
    header_content = generate_header(processed_icons, namespace)

    # Create output directory if it doesn't exist
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Write header file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header_content)

    print(f"✓ Generated {len(processed_icons)} icons in '{output_file}'")
    print(f"  Namespace: kalahari::icons::{namespace}")
    print(f"  File size: {len(header_content)} bytes")
    print("\nDone!")


if __name__ == "__main__":
    main()
